# NUMPY FUNC

In [144]:
# np.sort

import numpy as np

arr=np.random.randint(0,100,10).reshape(2,5)

In [145]:
print(arr)
print(np.sort(arr,axis=0)) # column wise sorting
print(np.sort(arr,axis=1)) # row wise sorting default 

[[ 8 30 14  7 52]
 [ 7 35 65 18 44]]
[[ 7 30 14  7 44]
 [ 8 35 65 18 52]]
[[ 7  8 14 30 52]
 [ 7 18 35 44 65]]


In [146]:
np.sort(arr,axis=1)

array([[ 7,  8, 14, 30, 52],
       [ 7, 18, 35, 44, 65]])

In [155]:
np.sort(arr)

array([[ 7,  8, 14, 30, 52],
       [ 7, 18, 35, 44, 65]])

In [148]:
arr[::-1].sort()

In [143]:
# np.append

arr=np.append(a,200)
arr

array([ 44.,  22.,   1.,  85.,  57.,   1.,  99.,   5.,   1.,   0.,  11.,
         1.,   7.,  30.,   1., 200.])

In [99]:
a=np.random.randint(0,100,10).reshape(5,2)
a=np.append(a,np.ones((a.shape[0],1)),axis=1)
a

array([[44., 22.,  1.],
       [85., 57.,  1.],
       [99.,  5.,  1.],
       [ 0., 11.,  1.],
       [ 7., 30.,  1.]])

In [124]:
np.append(a,np.random.random((a.shape[0],1)),axis=1)

array([[44.        , 22.        ,  1.        ,  0.83815947],
       [85.        , 57.        ,  1.        ,  0.66339894],
       [99.        ,  5.        ,  1.        ,  0.31378533],
       [ 0.        , 11.        ,  1.        ,  0.33214438],
       [ 7.        , 30.        ,  1.        ,  0.84322034]])

In [131]:
#np.concatenate

b = np.arange(6).reshape(2,3)
c = np.arange(6,12).reshape(2,3)

print(b)
print(c)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [132]:
np.concatenate((b,c),axis=0) # Row wise concatination 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [133]:
np.concatenate((b,c),axis=1) # Column wise concatination

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [157]:
#unique

e = np.array([1,2,2,3,3,4,4,5,6,7,8,9,9])

In [159]:
np.unique(e)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [160]:
#np.expand_dims - used to expand dimension with it's help we can get expanded dimensions of a numpy array.

e.shape

(13,)

In [161]:
np.expand_dims(e,axis=0).shape

(1, 13)

In [164]:
np.expand_dims(e,axis=0)

array([[1, 2, 2, 3, 3, 4, 4, 5, 6, 7, 8, 9, 9]])

In [162]:
np.expand_dims(e,axis=1).shape

(13, 1)

In [163]:
np.expand_dims(e,axis=1)

array([[1],
       [2],
       [2],
       [3],
       [3],
       [4],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9],
       [9]])

In [166]:
# np.where it will return the indices of elements where a given condition is satisfied.
arr2 = np.random.randint(1,100,25).reshape(5,5) 

In [168]:
np.where(arr2>50)

(array([0, 1, 1, 1, 1, 2, 3, 4, 4, 4], dtype=int64),
 array([0, 0, 1, 2, 3, 0, 3, 0, 1, 4], dtype=int64))

In [171]:
#  np.where(condition,true,false)

np.where(arr2>50,0,arr2)

array([[ 0, 29, 12, 41, 29],
       [ 0,  0,  0,  0,  4],
       [ 0, 44, 38, 16, 41],
       [34, 45,  9,  0, 47],
       [ 0,  0,  6, 45,  0]])

In [172]:
np.where(arr2>50,arr2,0)

array([[64,  0,  0,  0,  0],
       [51, 57, 87, 65,  0],
       [53,  0,  0,  0,  0],
       [ 0,  0,  0, 76,  0],
       [81, 55,  0,  0, 76]])

In [173]:
np.where(arr2%2==0,0,arr2)

array([[ 0, 29,  0, 41, 29],
       [51, 57, 87, 65,  0],
       [53,  0,  0,  0, 41],
       [ 0, 45,  9,  0, 47],
       [81, 55,  0, 45,  0]])

In [178]:
arr2

array([[64, 29, 12, 41, 29],
       [51, 57, 87, 65,  4],
       [53, 44, 38, 16, 41],
       [34, 45,  9, 76, 47],
       [81, 55,  6, 45, 76]])

In [183]:
#np.argmax it returns the indices of the max element of array in given axis.

np.argmax(arr2,axis=0)

array([4, 1, 1, 3, 4], dtype=int64)

In [180]:
np.argmin(arr2,axis=1)

array([2, 4, 3, 2, 2], dtype=int64)

In [202]:
for i,j in zip(np.argmax(arr2,axis=0),range(5)):
    print(arr2[i,j])

81
57
87
76
76


In [208]:
for j,i in zip(np.argmin(arr2,axis=1),range(5)):
    print(arr2[i,j])

12
4
16
9
6


In [213]:
arr2[0]

array([64, 29, 12, 41, 29])

In [210]:
# np.cumsum is used to find cumulative sum of the array for a given axis.
np.cumsum(arr2[0])

array([ 64,  93, 105, 146, 175], dtype=int32)

In [216]:
arr2[:,0]

array([64, 51, 53, 34, 81])

In [214]:
np.cumsum(arr2,axis=0) # for column 

array([[ 64,  29,  12,  41,  29],
       [115,  86,  99, 106,  33],
       [168, 130, 137, 122,  74],
       [202, 175, 146, 198, 121],
       [283, 230, 152, 243, 197]], dtype=int32)

In [218]:
np.cumprod(arr2,axis=1)

array([[      64,     1856,    22272,   913152, 26481408],
       [      51,     2907,   252909, 16439085, 65756340],
       [      53,     2332,    88616,  1417856, 58132096],
       [      34,     1530,    13770,  1046520, 49186440],
       [      81,     4455,    26730,  1202850, 91416600]], dtype=int32)

In [219]:
np.cumprod(arr2,axis=0)

array([[       64,        29,        12,        41,        29],
       [     3264,      1653,      1044,      2665,       116],
       [   172992,     72732,     39672,     42640,      4756],
       [  5881728,   3272940,    357048,   3240640,    223532],
       [476419968, 180011700,   2142288, 145828800,  16988432]],
      dtype=int32)

In [225]:
arr2

array([[64, 29, 12, 41, 29],
       [51, 57, 87, 65,  4],
       [53, 44, 38, 16, 41],
       [34, 45,  9, 76, 47],
       [81, 55,  6, 45, 76]])

In [222]:
# np.percentile it is used to compute the nth percentile of the given data

np.percentile(arr2,100)

87.0

In [223]:
np.percentile(arr2,0)

4.0

In [224]:
np.percentile(arr2,50)

45.0

In [226]:
arr2[arr2>np.percentile(arr2,50)]

array([64, 51, 57, 87, 65, 53, 76, 47, 81, 55, 76])

In [233]:
#np.histogram

arr2

array([[64, 29, 12, 41, 29],
       [51, 57, 87, 65,  4],
       [53, 44, 38, 16, 41],
       [34, 45,  9, 76, 47],
       [81, 55,  6, 45, 76]])

In [234]:
np.histogram(arr2,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([3, 2, 2, 2, 6, 4, 2, 2, 2, 0], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [235]:
np.histogram(arr2,bins=[0,50,100])

(array([15, 10], dtype=int64), array([  0,  50, 100]))

In [242]:
#np.corrcoef correlation-coefficient It returns the pearson product  

salary =np.array([20000,400000,500000,600000,10000000])

exp = np.array([1,2,1,3,3])

np.corrcoef(salary,exp)

array([[1.        , 0.58498633],
       [0.58498633, 1.        ]])

In [243]:
#np.isin 

items = [47,4,16,6,87]

np.isin(arr2,items)

array([[False, False, False, False, False],
       [False, False,  True, False,  True],
       [False, False, False,  True, False],
       [False, False, False, False,  True],
       [False, False,  True, False, False]])

In [246]:
arr2[np.isin(arr2,items)]

(5,)

In [249]:
arr2

array([[64, 29, 12, 41, 29],
       [51, 57, 87, 65,  4],
       [53, 44, 38, 16, 41],
       [34, 45,  9, 76, 47],
       [81, 55,  6, 45, 76]])

In [250]:
# flip it reverses the order of the array element along the specified axis preserving the shape of the array.

np.flip(arr2,axis=1) #row wise flip

array([[29, 41, 12, 29, 64],
       [ 4, 65, 87, 57, 51],
       [41, 16, 38, 44, 53],
       [47, 76,  9, 45, 34],
       [76, 45,  6, 55, 81]])

In [252]:
np.flip(arr2)

array([[76, 45,  6, 55, 81],
       [47, 76,  9, 45, 34],
       [41, 16, 38, 44, 53],
       [ 4, 65, 87, 57, 51],
       [29, 41, 12, 29, 64]])

In [251]:
np.flip(arr2,axis=0)

array([[81, 55,  6, 45, 76],
       [34, 45,  9, 76, 47],
       [53, 44, 38, 16, 41],
       [51, 57, 87, 65,  4],
       [64, 29, 12, 41, 29]])