## Numpy array vs Python lists

- python numpy array are preferred over lists because they consume less space , memory and offers faster and easier computation.

In [1]:
# speed

a = [i for i in range(10000000)]

b = [i for i in range(10000000,20000000)]

c = []

import time
start= time.time()

for i in range(len(a)):
    c.append(a[i]+b[i])
print(time.time()-start)

7.178617715835571


In [2]:
import numpy as np

a = np.arange(10000000)

b = np.arange(10000000,20000000)

start = time.time()

c = a+b

print(time.time()-start)

0.24007534980773926


In [3]:
a = [i for i in range(10000000)]

import sys 

sys.getsizeof(a)

89095160

In [4]:
a=np.arange(10000000)
sys.getsizeof(a)

40000104

In [5]:
l=[1,'aryan',2,2.33]

In [6]:
l[1][::-1]

'nayra'

In [7]:
l=[1,[1,2,[1,2,3,[1,2,3,4,[1,2,3,4,5]]]]]

In [8]:
l[1][2][3][::-1][3]

2

# Advanced Indexing

In [9]:
a = np.arange(12).reshape(3,4)

In [10]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
a[0:2,0:2]

array([[0, 1],
       [4, 5]])

In [12]:
a[::2]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [13]:
# Fancy Indexing

a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [14]:
a[[0,1,3]]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [15]:
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [16]:
# Boolean Indexing

arr = np.random.randint(1,100,24).reshape(8,3)

In [17]:
arr[arr > 50]

array([69, 62, 56, 90, 62, 76, 54, 68, 66, 76, 66, 67, 60])

In [18]:
arr[arr%2==0]

array([46, 44, 62, 42, 56, 90, 12, 62, 14, 76, 54, 68, 66, 76,  8, 66, 60])

In [19]:
arr[(arr > 50) & (arr%2==0)]  ## Use bitwise and (&) because we are working with boolean values

array([62, 56, 90, 62, 76, 54, 68, 66, 76, 66, 60])

In [20]:
arr[arr % 7==0]

array([42, 56, 14, 35])

In [21]:
arr[arr % 7!=0]

array([46, 69, 44, 62, 90, 12, 62, 15, 76,  5, 54, 68, 11, 66, 76,  8, 66,
       67, 27, 60])

In [22]:
arr[~(arr % 7==0)]

array([46, 69, 44, 62, 90, 12, 62, 15, 76,  5, 54, 68, 11, 66, 76,  8, 66,
       67, 27, 60])

# Broadcasting

The term broadcasting treats array of different shapes during arithmetic operations.

The smaller array is "broadcast" across larger array so that they have compatible size.

In [23]:
arr1 = np.arange(6).reshape(2,3)

arr2 = np.arange(3)


print(arr1)

print(arr2)

[[0 1 2]
 [3 4 5]]
[0 1 2]


In [24]:
arr1+arr2

array([[0, 2, 4],
       [3, 5, 7]])

In [25]:
np.full((2,3),2)

array([[2, 2, 2],
       [2, 2, 2]])

### Broadcasting Rules

1. Make the two arrays have the same number of dimensions.
   -   If the numbers of dimensions of the two arrays are different , add new dimensions with size 1 to the head of the array with the smaller dimensions.

2. Make each dimensions of the two array of the same size.
      - If the size of each dimensions of the array do not match , dimensions with size 1 are stretched to size of the other array.
      - If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted and an error is raised.

In [26]:
a = np.arange(3).reshape(1,3)

b = np.arange(3).reshape(3,1)

print(a)
print(b)

a + b

[[0 1 2]]
[[0]
 [1]
 [2]]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [27]:
a = np.arange(12).reshape(3,4)

b = np.arange(12).reshape(4,3)

print(a)

print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [28]:
a = np.arange(16).reshape(4,4)

b = np.arange(4).reshape(2,2)

print(a)

print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]


ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 

# Working with mathematical formulas

In [29]:
#sigmoid
def sigmoid(array):
    return np.exp(array)/(np.exp(array)+1)


a = np.arange(10)

sigmoid(a)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661])

In [30]:
#mean square error

actual =  np.random.randint(1,50,25)

predict = np.random.randint(1,50,25)


In [31]:
def mse(actual,predicted):
        return np.mean((actual - predicted)**2 )

In [32]:
mse(actual,predict)

465.44

In [56]:
#binary cross entropy

def binary_cross_entropy(actual,predicted):
    return -np.mean((actual * np.log(predicted))+((1-actual) * (np.log(predicted))))

In [57]:
binary_cross_entropy(actual,predict)

-2.7525621544695853

In [53]:
np.log(predict)

array([3.71357207, 3.80666249, 1.38629436, 3.63758616, 3.66356165,
       3.4339872 , 2.83321334, 0.        , 2.56494936, 3.09104245,
       3.21887582, 3.52636052, 3.58351894, 3.25809654, 3.21887582,
       3.76120012, 1.94591015, 2.07944154, 3.71357207, 2.77258872,
       2.7080502 , 3.76120012, 0.        , 3.13549422, 0.        ])

## Working with missing values

In [ ]:
a= np.array([1,2,3,4,np.nan,6])
a

In [ ]:
a[~(np.isnan(a))]

# Plotting graphs

In [ ]:
x = np.linspace(-10,10,100)
y = x

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.plot(x,y)

In [ ]:
y = x**2

In [ ]:
plt.plot(x,y)


In [ ]:
y = np.sin(x)

In [ ]:
plt.plot(x,y)

In [ ]:
y = x*np.log(x)

In [ ]:
plt.plot(x,y)

In [ ]:
## sigmoid graph

y = sigmoid(x)

In [ ]:
plt.plot(x,y)