# NUMPY FUNC

In [7]:
# np.sort

import numpy as np

a=np.random.randint(0,100,10).reshape(2,5)

In [14]:
print(a)
print(np.sort(a,axis=0)) # column wise sorting
print(np.sort(a,axis=1)) # row wise sorting default 

[[20 68 20 86 31]
 [31 75 39 67 49]]
[[20 68 20 67 31]
 [31 75 39 86 49]]
[[20 20 31 68 86]
 [31 39 49 67 75]]


In [25]:
np.sort(a,axis=1)

array([[20, 20, 31, 68, 86],
       [31, 39, 49, 67, 75]])

In [27]:
# np.append

a=np.append(a,200)
a

array([ 20,  68,  20,  86,  31,  31,  75,  39,  67,  49, 200])