## Numpy array vs Python lists

- python numpy array are preferred over lists because they consume less space , memory and offers faster and easier computation.

In [4]:
# speed

a = [i for i in range(10000000)]

b = [i for i in range(10000000,20000000)]

c = []

import time
start= time.time()

for i in range(len(a)):
    c.append(a[i]+b[i])
print(time.time()-start)

6.384644985198975


In [5]:
import numpy as np

a = np.arange(10000000)

b = np.arange(10000000,20000000)

start = time.time()

c = a+b

print(time.time()-start)

0.22898554801940918


'Thu Apr  6 20:46:48 2023'

In [6]:
a = [i for i in range(10000000)]

import sys 

sys.getsizeof(a)

89095160

In [7]:
a=np.arange(10000000)
sys.getsizeof(a)

40000104

In [8]:
l=[1,'aryan',2,2.33]

In [9]:
l[1][::-1]

'nayra'

In [10]:
l=[1,[1,2,[1,2,3,[1,2,3,4,[1,2,3,4,5]]]]]

In [17]:
l[1][2][3][::-1][3]

2

# Advanced Indexing

In [18]:
a = np.arange(12).reshape(3,4)

In [19]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
a[0:2,0:2]

array([[0, 1],
       [4, 5]])

In [36]:
a[::2]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [45]:
# Fancy Indexing

a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [46]:
a[[0,1,3]]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [49]:
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [54]:
# Boolean Indexing

arr = np.random.randint(1,100,24).reshape(8,3)

array([[41, 80, 40],
       [13, 72, 97],
       [64, 99, 52],
       [41, 31, 60],
       [70, 34, 81],
       [92, 32, 10],
       [83, 60, 30],
       [ 5, 34, 91]])

In [56]:
arr[arr > 50]

array([80, 72, 97, 64, 99, 52, 60, 70, 81, 92, 83, 60, 91])

In [57]:
arr[arr%2==0]

array([80, 40, 72, 64, 52, 60, 70, 34, 92, 32, 10, 60, 30, 34])

In [60]:
arr[(arr > 50) & (arr%2==0)]  ## Use bitwise and (&) because we are working with boolean values

array([80, 72, 64, 52, 60, 70, 92, 60])

In [61]:
arr[arr % 7==0]

array([70, 91])

In [62]:
arr[arr % 7!=0]

array([41, 80, 40, 13, 72, 97, 64, 99, 52, 41, 31, 60, 34, 81, 92, 32, 10,
       83, 60, 30,  5, 34])

In [64]:
arr[~(arr % 7==0)]

array([41, 80, 40, 13, 72, 97, 64, 99, 52, 41, 31, 60, 34, 81, 92, 32, 10,
       83, 60, 30,  5, 34])

# Broadcasting

The term broadcasting treats array of different shapes during arithmetic operations.

The smaller array is "broadcast" across larger array so that they have compatible size.

In [65]:
arr1 = np.arange(6).reshape(2,3)

arr2 = np.arange(3)


print(arr1)

print(arr2)

[[0 1 2]
 [3 4 5]]
[0 1 2]


In [66]:
arr1+arr2

array([[0, 2, 4],
       [3, 5, 7]])

In [74]:
np.full((2,3),2)

array([[2, 2, 2],
       [2, 2, 2]])

### Broadcasting Rules

1. Make the two arrays have the same number of dimensions.
   -   If the numbers of dimensions of the two arrays are different , add new dimensions with size 1 to the head of the array with the smaller dimensions.

2. Make each dimensions of the two array of the same size.
      - If the size of each dimensions of the array do not match , dimensions with size 1 are stretched to size of the other array.
      - If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted and an error is raised.

In [76]:
a = np.arange(3).reshape(1,3)

b = np.arange(3).reshape(3,1)

print(a)
print(b)

a + b

[[0 1 2]]
[[0]
 [1]
 [2]]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [80]:
a = np.arange(12).reshape(3,4)

b = np.arange(12).reshape(4,3)

print(a)

print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [81]:
a = np.arange(16).reshape(4,4)

b = np.arange(4).reshape(2,2)

print(a)

print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]


ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 