In [1]:
import numpy as np


In [2]:
# seeing the numpy version.

np.__version__

'1.20.3'

In [4]:
# create a 1d numpy array

a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [11]:
# create a boolean array

b = np.full((9),True,dtype=bool).reshape(3,3)
print(b)
b_ones = np.ones((3,3),dtype=bool)
print(b_ones)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [13]:
# extracting items that satisfy a condition

print(a[a>3],a[a%2==0])

[4 5 6 7 8 9] [2 4 6 8]


In [15]:
# replace the item that satisfy a particular condition by a certain item

a[a>3]=0
print(a)

[1 2 3 0 0 0 0 0 0]


In [19]:
# replacing items such that they didn't affect our original array

a = np.arange(10)

new_arr = a.copy()

new_arr[new_arr%2 == 0] = -1

print(new_arr,a)

[-1  1 -1  3 -1  5 -1  7 -1  9] [0 1 2 3 4 5 6 7 8 9]


In [21]:
# reshaping an array

arr = np.arange(10) # created the 1-D array

arr.reshape(2,5)    # reshaping the 1-D array into 2 * 5 configuration

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
# stack two arrays vertically

arr = arr.reshape(2,5)

brr = arr.copy()

np.vstack((arr,brr)) # vstack will take a tuple as an argument.

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
# stack two arrays horizontally

arr = arr.reshape(2,5)

brr = arr.copy()

np.hstack((arr,brr))

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

In [29]:
# Question: Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

a = np.array([1,2,3])


np.hstack([np.repeat(a,3),np.tile(a,3)])


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [35]:
# get common items between two numpy array


arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,4])

np.intersect1d(arr1,arr2)

array([1, 2, 4])

In [37]:
xy,x_ind,y_ind=np.intersect1d(arr1,arr2,return_indices=True)

In [38]:
print(xy,x_ind,y_ind)

[1 2 4] [0 1 3] [0 1 2]


In [40]:
# remove elements which exist only in other array

np.setdiff1d(arr1,arr2)

array([3, 5])

In [43]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [47]:
# extract all the number between 5 and 10 from a
a = np.array([2, 6, 1, 9, 10, 3, 27])

a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

In [51]:
# Convert the function maxx on two scalars two work on two arrays

def maxx(x,y):
    if x > y:
        return x
    else:
        return y
    
def maxx_taker(x,y):
    maximum = [maxx(a,b) for a,b in zip(x,y)]
    return np.array(maximum)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

maxx_taker(a,b)

array([6, 7, 9, 8, 9, 7, 5])

In [60]:
# swaping two rows in numpy 2d array

arr1 =  np.arange(10).reshape(2,5)

print('\nOriginal Array:\n',arr1)
print('\nModified Array:\n',arr1[:,[1,0,4,3,2]])


Original Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

Modified Array:
 [[1 0 4 3 2]
 [6 5 9 8 7]]


In [63]:
# reversing colums of a 2d array

print('\nOriginal Array:\n',arr1)

print('\nModified Array:\n',arr1[:,::-1])


Original Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

Modified Array:
 [[4 3 2 1 0]
 [9 8 7 6 5]]


In [64]:
# reversing rows of a 2d array

print('\nOriginal Array:\n',arr1)

print('\nModified Array:\n',arr1[::-1,:])


Original Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

Modified Array:
 [[5 6 7 8 9]
 [0 1 2 3 4]]


In [77]:
# create a 2d numpy array containing random float numper between 3 and 10


np.random.uniform(3,10,size = (3,3))

array([[7.88428619, 4.85398872, 4.96933418],
       [4.37950371, 4.8308356 , 8.91604639],
       [8.22247586, 6.71793122, 7.77175145]])

In [79]:
# print only 3 decimal places in numpy array

rand_arr = np.random.random((2,3))
np.set_printoptions(precision=3)
rand_arr

array([[0.573, 0.88 , 0.451],
       [0.453, 0.444, 0.508]])

In [105]:
rand_arr = np.random.random((2,3))
np.set_printoptions(suppress = True)
rand_arr

array([[0.077, 0.772, 0.572],
       [0.401, 0.11 , 0.379]])

In [127]:
# limiting number of item prinited in array 

a = np.arange(30)

# np.set_printoptions(threshold=4)
a

array([ 0,  1,  2, ..., 27, 28, 29])

In [137]:

# b = np.arange(30)

# np.set_printoptions(threshold=4)
# b

array([ 0,  1,  2, ..., 27, 28, 29])

In [142]:
### create an identity numpy array of order 3
np_arr = np.identity(3,dtype='int16')

print(np_arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [144]:
print(type(np_arr),np_arr.dtype)

<class 'numpy.ndarray'> int16


In [147]:
np.arange(5,11,1)

array([ 5,  6,  7,  8,  9, 10])

In [148]:
np.arange(5,11,2)

array([5, 7, 9])

In [151]:
np.arange(5,7,.4)

array([5. , 5.4, 5.8, 6.2, 6.6])

In [155]:
np.random.randint(0,10,5)

array([9, 4, 5, 7, 9])

In [154]:
np.random.uniform(0,10,size = 5)

array([3.563, 0.304, 9.056, 6.923, 2.369])